config/routes.rb
Rails.application.routes.draw do
  

  resources :user_profiles

  get 'contact' => 'static_pages#contact'

  get 'about' => 'static_pages#about'

  devise_for :users
  
  root to: 'static_pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :user_profile
end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
	belongs_to :user
	mount_uploader :avatar, AvatarUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end

  def about
  end
end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController
before_action :authenticate_user!, only: [:new,:show, :edit]
before_action :find_user_profiles, only: [:show, :edit, :update, :destroy]

	def new
	 @user_profile = current_user.build_user_profile 
	end

	def create
		@user_profile = current_user.build_user_profile(user_params)

		if @user_profile.save

			 flash[:notice] = "welcome #{current_user.username}"
			redirect_to @user_profile
		else

			render :new
		end
	end

	def edit
	end

	def update
		if @user_profile.update_attributes(user_params)

			flash[:notice] = "profile successfully updated"
			redirect_to @user_profile
		else
			render :edit
		end
	end

	def show
	end

	# def delete
	# end

	# def destroy
	# 	@user_profile.destroy
	# 	redirect_to root_path
	# end


private

	def find_user_profiles
		@user_profile = UserProfile.find(params[:id])
	end

    def user_params
     params.require(:user_profile).permit(:username, :bio, :avatar, :sex, :age)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

app/views/layouts/_fab.html.erb
<div class="fixed-action-btn" style="bottom: 3.3em; right: 0.2em;">
	<a class="btn-floating btn-large halfway-fab waves-effect waves-light teal">
		<i class="material-icons">mode_edit</i>
	</a>
</div>

app/views/layouts/_footer.html.erb
 <footer class="page-footer">
   <div class="container">
     <div class="row">
       <div class="col l6 s12">
         <h5 class="white-text">Footer Content</h5>
         <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
       </div>
       <div class="col l4 offset-l2 s12">
         <h5 class="white-text">Links</h5>
         <ul>
           <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
           <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
           <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
           <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
         </ul>
       </div>
     </div>
   </div>
   <div class="footer-copyright">
     <div class="container">
       © 2017 Copyright Text
       <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
     </div>
   </div>
 </footer>

app/views/layouts/_main_nav.html.erb
<nav class="nav-extended">
  <div class="nav-wrapper">
    <%= link_to("DEJAF", root_path, class: "brand-logo")%>
    <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <li><%= link_to("Home", root_path)%></li>
      <li><%= link_to("Sign Up", new_user_registration_path)%></li>
      <li><%= link_to("Login", new_user_session_path)%></li>
    </ul>
    <ul class="side-nav" id="mobile-demo">
      <li><a href="sass.html">Sass</a></li>
      <li><a href="badges.html">Components</a></li>
      <li><a href="collapsible.html">JavaScript</a></li>
    </ul>
  </div>
  <div class="nav-content">
    <ul class="tabs tabs-transparent">
      <li class="tab"><a href="#test1">Home</a></li>
      <li class="tab"><a href="#test3">Events</a></li>
      <li class="tab"><a href="#test4">Vacancy</a></li>
    </ul>
    
  </div>
</nav>
  <div id="test1" class="col s12"><% StaticPagesController.render('home') %></div>
  <div id="test3" class="col s12">Test 3</div>
  <div id="test4" class="col s12">Test 4</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dejaf <%= yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<header>
      <% if !current_page?(new_user_registration_path) &&  !current_page?(new_user_session_path) && !current_page?(new_user_profile_path)  %>
  		  <%= render '/layouts/main_nav'%>
      <% end %>
  	</header>
  	<main>
	  	<section class="message">
	  		<p class="notice"><%= notice %></p>
       	<p class="alert"><%= alert %></p>
	  	</section>
  		<section class="main-section">
  			<%= yield %>
  		</section>
      <% if !current_page?(new_user_registration_path) &&  !current_page?(new_user_session_path) && !current_page?(new_user_profile_path)%>
        <%= render '/layouts/fab'%>
      <% end %>
      
      
  	</main>
    <% if !current_page?(new_user_registration_path) &&  !current_page?(new_user_session_path) && !current_page?(new_user_profile_path) %>
      <footer>
        <%= render '/layouts/footer'%>
      </footer>
    <% end %>

  </body>
</html>

app/views/static_pages/_carousel.html.erb
<div class="carousel carousel-slider center" data-indicators="true">
  <div class="carousel-fixed-item center">
    <a class="btn waves-effect white grey-text darken-text-2">button</a>
  </div>
  <div class="carousel-item red white-text" href="#one!">
    <h2>First Panel</h2>
    <p class="white-text">This is your first panel</p>
  </div>
  <div class="carousel-item amber white-text" href="#two!">
    <h2>Second Panel</h2>
    <p class="white-text">This is your second panel</p>
  </div>
  <div class="carousel-item green white-text" href="#three!">
    <h2>Third Panel</h2>
    <p class="white-text">This is your third panel</p>
  </div>
  <div class="carousel-item blue white-text" href="#four!">
    <h2>Fourth Panel</h2>
    <p class="white-text">This is your fourth panel</p>
  </div>
</div>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/home.html.erb
<%= render '/static_pages/carousel' %>

app/views/user_profiles/edit.html.erb
<h1>UserProfiles#edit</h1>
<p>Find me in app/views/user_profiles/edit.html.erb</p>

app/views/user_profiles/new.html.erb
<% provide(:title, "| Setting Up Profile") %>
<div class="contanier">
	<div class="row">
		<div class="col l8 offset-l2">

			<div class="card">
				<div class="card-content">
					<span class="center"><%= link_to image_tag("3", :alt => "logo"), root_path %></span>
					<span class="card-title">Create User Profile</span>
					<%=	form_for(@user_profile)	do	|f|	%>
						<div class="row">
							<div class="col l4">
								<div class="file-uplaod">
									<%= image_tag("avatar", class: "responsive-img", size: "200x300") %>
								 	<%= f.file_field :avatar%>
								</div>
								 
    						</div>
							<div class="col l8">
								<div class="input-field">
									<%=	f.text_field :username ,placeholder: "Username",class: "validate"%>
								</div>
								<div class="row">
									<div class="col l3">
										<div class="input-field">
											<%=	f.text_field :age ,placeholder: "Age",class: "validate"%>
										</div>
									</div>
									<div class="input-field col l3">
									    <select name="user_profile[sex]" id="user_profile_sex">
									      <option value="male">Male</option>
									      <option value="female">Female</option>
									    </select>
				
									</div>
									<div class="col l4"></div>
								</div>
								<div class="input-field">
									<i class="material-icons prefix">mode_edit</i>
									<%= f.text_area :bio, class: "materialize-textarea", length:"140" %>
									<%= f.label :bio, "bio"%>
								</div>

							</div>
						</div>
						<div class="actions center">
              				<span><%= f.button "Create Profile", :class => "btn waves-effect waves-light btn-large"%></span>
            			</div>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>